stages:
  - build

build-image:
  stage: build

  script:
    - docker version

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    - docker build \
      -t $DOCKER_USERNAME/cloudshop-product-service:$CI_COMMIT_SHORT_SHA \
      services/product-service

    - docker push \
      $DOCKER_USERNAME/cloudshop-product-service:$CI_COMMIT_SHORT_SHA
