apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: cloudshop
spec:
  replicas: {{ .Values.product.replicaCount }}

  selector:
    matchLabels:
      app: product-service

  template:
    metadata:
      labels:
        app: product-service

    spec:
      containers:
      - name: product-service
        image: "{{ .Values.product.image }}"
        imagePullPolicy: Never

        ports:
        - containerPort: 8000
