namespace: cloudshop

productService:
  replicaCount: 1

  image:
    repository: kunalsambharwal36/cloudshop-product-service
    tag: v5
    pullPolicy: Always

  containerPort: 8000

  service:
    type: ClusterIP
    port: 80
    targetPort: 8000

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

  hpa:
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50

orderService:
  replicaCount: 1

  image:
    repository: kunalsambharwal36/cloudshop-order-service
    tag: v5
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 80
    targetPort: 8000
  
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

    limits:
      cpu: 500m
      memory: 512Mi

consumer:
  replicaCount: 1

  image:
    repository: kunalsambharwal36/cloudshop-order-consumer
    tag: v5
    pullPolicy: Always
    
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

    limits:
      cpu: 500m
      memory: 512Mi

kafka:
  bootstrap: cloudshop-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092

database:
  url: postgresql://postgres:admin123@postgres-postgresql.database.svc.cluster.local:5432/cloudshop
